### ISSUE TITLE
Switching signature results in two signature separators with Emacs 28.2

### ISSUE THREAD

**Issue by tardigradus** [hexmode/gnus-alias#6]
I recently up dated from Debian 11 to Debian 12 and hence from Emacs 27.1 to Emacs 28.2.  I now find that when I switch between aliases, a second signature separator is added.  So
 
    -- 
    Sig A

becomes

    -- 
    -- 
    Sig B

I assume there is some issue with the way the beginning of the signature is identified.

**Comment by tardigradus** [comment]
In the function

    gnus-alias-goto-sig

replacing the final line

    (beginning-of-line)))

with

    (forward-line 0)))

solves the problem.  I am not sure how this change would affect Emacs 27 or earlier.

**Comment by hexmode** [comment]
Thanks!  Should be working now.

**Comment by Thaodan** [comment]
While checking out Gnus alias for some other stuff I noticed that you removed the original copyright, Then previous copyright should be placed under the new one.
